services:
  - type: web
    name: gestion-snack-backend
    runtime: docker
    plan: free
    rootDir: Backend_gestion_snack
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api-docs
    envVars:
      - key: DATABASE_URL
        sync: false   # jdbc:postgresql://...neon.tech/neondb?sslmode=require&channel_binding=require&stringtype=unspecified
      - key: DATABASE_USERNAME
        sync: false   # neondb_owner
      - key: DATABASE_PASSWORD
        sync: false   # mot de passe Neon.tech
      - key: APP_BASE_URL
        sync: false   # https://gestion-snack-backend.onrender.com
      - key: ALLOWED_ORIGINS
        sync: false   # https://votre-app.vercel.app
