import { createContext, useContext, useState } from 'react';

const translations = {
  fr: {
    // Navbar
    nav: {
      dashboard: 'Tableau de bord',
      users: 'Utilisateurs',
      products: 'Produits',
      orders: 'Commandes',
      menu: 'Menu',
      myOrders: 'Mes commandes',
      myReservations: 'Mes réservations',
      myReviews: 'Mes avis',
      payments: 'Paiements',
      ordersToServe: 'Commandes à servir',
      tableManagement: 'Gestion des tables',
      ordersToPrep: 'Commandes à préparer',
      supplyOrders: 'Bons de commande',
      mySupplies: 'Mes fournitures',
      profile: 'Mon profil',
      logout: 'Déconnexion',
      about: 'À Propos',
      restaurantSettings: 'Paramètres',
    },
    // Footer
    footer: {
      description: 'Système de gestion complet de snack. Gestion des commandes, réservations, stocks et bien plus encore.',
      quickLinks: 'Liens rapides',
      about: 'À propos',
      contact: 'Contact',
      info: 'Informations',
      rights: 'Tous droits réservés.',
      devWith: 'Développé avec React et Spring Boot',
      address: 'Adresse',
      phone: 'Téléphone',
      email: 'E-mail',
      hours: "Horaires d'ouverture",
      hoursDetails: 'Lun-Sam: 10h00 - 22h00 | Dim: 12h00 - 21h00',
      open: 'Ouvert maintenant',
      closed: 'Fermé actuellement',
      location: 'Notre localisation',
      weekdays: 'Lun – Sam',
      sunday: 'Dim',
      mapsOpen: 'Ouvrir sur Google Maps',
    },
    // Dashboard admin
    dashboard: {
      title: 'Tableau de bord Administrateur',
      users: 'Utilisateurs',
      employees: 'Employés',
      providers: 'Fournisseurs',
      products: 'Produits',
      clientOrders: 'Commandes Clients',
      supplierOrders: 'Commandes Fournisseurs',
      tables: 'Tables',
      stockAlerts: 'Alertes Stock',
      revenue: 'Chiffre d\'affaires',
      tickets: 'Tickets',
      manageUsers: 'Gérer les utilisateurs',
      manageStaff: 'Gérer le personnel',
      manageProviders: 'Gérer les fournisseurs',
      manageStock: 'Gérer le stock',
      viewOrders: 'Voir les commandes',
      viewSupplies: 'Voir les approvisionnements',
      manageHall: 'Gérer la salle',
      viewAlerts: 'Voir les alertes',
      financialDetails: 'Détails financiers',
      manageTickets: 'Gérer les tickets',
      quickActions: 'Actions Rapides',
      newProduct: 'Nouveau Produit',
      newEmployee: 'Nouvel Employé',
      newProvider: 'Nouveau Fournisseur',
      orderStock: 'Commander Stock',
      newTable: 'Nouvelle Table',
      recentActivity: 'Activité Récente',
      recentOrders: 'Commandes Récentes',
      recentReviews: 'Derniers Avis Clients',
      topProducts: 'Top Produits',
      reservationStats: 'Statistiques Réservations',
      ordersByStatus: 'Commandes par Statut',
      todayRevenue: "Chiffre d'affaires Aujourd'hui",
      totalRevenue: 'Chiffre d\'affaires Total',
      avgOrderValue: 'Panier Moyen',
      noReviews: 'Aucun avis disponible',
      noOrders: 'Aucune commande récente',
      loading: 'Chargement...',
      refreshEvery: 'Actualisation toutes les 30 sec',
      ordersActive: 'Actives',
      ordersClosed: 'Prêtes',
      ordersServed: 'Servies',
      ordersCancelled: 'Annulées',
      booked: 'Réservées',
      completed: 'Terminées',
      cancelled: 'Annulées',
      noData: 'Pas de données',
      refresh: 'Actualiser',
      ordersCount: 'commandes',
      today: "Aujourd'hui",
      perOrder: 'Par commande',
      viewAll: 'Voir tout →',
      last5: '5 derniers',
      weeklyOrders: 'Commandes - 7 derniers jours',
      weeklyRevenue: "Chiffre d'affaires - 7 jours",
      totalLabel: 'Total :',
      totalReservations: 'Total réservations',
      onSite: 'Sur place',
      takeaway: 'À emporter',
    },
    // Menu
    menu: {
      title: 'C\'est l\'heure de se',
      titleHighlight: 'Régaler !',
      subtitle: 'Découvrez nos délicieux plats préparés avec passion et servis avec le sourire.',
      search: 'Un petit creux ? Cherchez ici...',
      allCategories: 'Toutes les catégories',
      ourDishes: 'Nos Plats',
      freshDrinks: 'Boissons Fraîches',
      nothingFound: 'Oups ! Rien n\'a été trouvé',
      tryAnother: 'Essayez une autre recherche ou catégorie',
      checkout: 'Passer la commande',
      article: 'Article',
      articles: 'Articles',
      productDetails: 'Détails de l\'article',
      unitPrice: 'Prix Unitaire',
      availability: 'Disponibilité',
      outOfStock: 'En rupture',
      lowStock: 'Stock faible',
      available: 'Disponible',
      description: 'Description',
      allergens: 'Allergènes',
      noAllergens: 'Aucun allergène déclaré',
      yourRating: 'Votre Note / Avis Produit',
      ratedWith: 'Vous avez attribué',
      stars: 'étoiles',
      addToCart: 'Ajouter au Panier',
      unavailable: 'Indisponible',
      close: 'Fermer',
      // Extras
      chooseSauces: 'Choisissez vos Sauces',
      chooseViandes: 'Choisissez votre Viande',
      chooseDesserts: 'Choisissez un Dessert',
      extras: 'Extras & Options',
      basePrice: 'Prix de base',
      extrasTotal: 'Total extras',
      totalPrice: 'Prix Total',
      viewDetails: 'Voir les détails',
      outOfStockMsg: 'Désolé, ce produit est en rupture de stock.',
    },
    // ProductCard
    card: {
      outOfStock: 'Rupture de stock',
      lowStock: 'Stock faible',
      seeDetails: 'Voir les détails',
      addToCart: 'Ajouter au panier',
      inCart: 'Dans le panier',
      unavailable: 'Indisponible',
      remaining: 'restants',
      exhausted: 'Épuisé',
    },
    // Chatbot
    chatbot: {
      title: 'Service Client IA',
      online: 'En ligne',
      welcome: 'Bonjour ! Je suis l\'assistant du Snack Tiegni Bernard. Comment puis-je vous aider aujourd\'hui ?',
      placeholder: 'Écrivez votre message...',
      generatedByAI: 'Généré par l\'IA - Peut commettre des erreurs',
      retry: 'Réessayer',
      unstableConnection: 'Connexion instable...',
      errorMessage: 'Désolé, je rencontre des difficultés techniques pour vous répondre. Veuillez réessayer.',
      openChat: 'Ouvrir le chat avec le service client',
      closeChat: 'Fermer le chat',
      send: 'Envoyer',
      voiceInput: 'Entrée vocale',
      listening: 'Je vous écoute...',
      voiceError: 'Erreur microphone - vérifiez les permissions',
      voiceNotSupported: 'Entrée vocale non supportée par ce navigateur',
      liveVoice: 'Chat Vocal Live',
      voiceFirefoxNotSupported: 'Firefox ne supporte pas la reconnaissance vocale. Utilisez Chrome, Edge ou Safari.',
      voiceMicDenied: 'Accès au microphone refusé. Vérifiez les paramètres de votre navigateur.',
      voiceMicNotFound: 'Aucun microphone détecté sur cet appareil.',
    },
    // About
    about: {
      heroTitle: 'Snack Tiegni Bernard',
      heroSubtitle: 'Votre restaurant au cœur de Bruxelles, Belgique',
      story: 'Notre Histoire',
      storyText: 'Fondé avec passion, le Snack Tiegni Bernard est un restaurant moderne alliant saveurs belges authentiques et inspirations internationales. Situé au cœur de Bruxelles, nous proposons une expérience gastronomique unique avec des produits frais et de qualité, servis avec le sourire.',
      mission: 'Notre Mission',
      missionText: 'Offrir à nos clients une expérience culinaire exceptionnelle dans un cadre chaleureux, avec un service rapide et des prix abordables pour tous.',
      contact: 'Nous Contacter',
      address: 'Adresse',
      phone: 'Téléphone',
      email: 'E-mail',
      hours: "Horaires d'Ouverture",
      weekdays: 'Lundi – Samedi',
      sunday: 'Dimanche',
      weekdaysHours: '10h00 – 22h00',
      sundayHours: '12h00 – 21h00',
      open: 'Ouvert maintenant',
      closed: 'Fermé actuellement',
      location: 'Notre Localisation',
      mapLink: 'Voir sur Google Maps',
      values: 'Nos Valeurs',
      quality: 'Qualité',
      qualityDesc: 'Ingrédients frais sélectionnés avec soin chaque jour',
      service: 'Service',
      serviceDesc: 'Accueil chaleureux et équipe dédiée à votre satisfaction',
      speed: 'Rapidité',
      speedDesc: 'Préparation rapide sans jamais sacrifier la qualité',
      team: 'Notre Équipe',
      teamDesc: 'Des professionnels passionnés à votre service',
      viewMenu: 'Voir notre menu',
      orderNow: 'Commander maintenant',
      contactUs: 'Nous contacter',
      followUs: 'Suivez-nous',
      copyright: 'Tous droits réservés',
      locationCity: 'Bruxelles, Belgique',
      roleAdmin: 'Administrateur',
      roleAdminDesc: 'Supervision globale du restaurant et des opérations',
      roleCashier: 'Caissier',
      roleCashierDesc: 'Gestion des paiements et validation des transactions',
      roleCook: 'Cuisinier',
      roleCookDesc: 'Préparation des commandes et gestion de la cuisine',
      roleWaiter: 'Serveur',
      roleWaiterDesc: 'Service en salle, attribution des tables et réservations',
      mapInteractive: 'Carte interactive',
      viewOnMaps: 'Voir sur Google Maps',
    },
    // Checkout
    checkout: {
      title: 'Votre Panier',
      summary: 'Récapitulatif',
      empty: 'Votre panier est vide',
      emptyDesc: 'Ajoutez des produits depuis le menu pour commencer',
      backToMenu: 'Retour au menu',
      orderType: 'Type de commande',
      paymentMethod: 'Méthode de paiement',
      documentType: 'Type de document',
      pickupTime: 'Heure de retrait (optionnel)',
      pickupHint: 'Laissez vide pour un retrait immédiat',
      guestCount: 'Nombre de couverts',
      guestHint: 'Le serveur vous attribuera une table',
      total: 'Total',
      base: 'Sous-total',
      extras: 'Extras',
      order: 'Commander',
      pay: 'Payer',
      processing: 'Traitement...',
      includes: 'inclus',
      ordersSection: 'Articles commandés',
      orderOptions: 'Options de commande',
      typeLabel: 'Type',
      securePayment: 'Paiement sécurisé · Données protégées',
      paymentLabel: 'Paiement',
      documentLabel: 'Document',
      retrievalLabel: 'Retrait',
      successOnSite: 'Commande envoyée en cuisine !',
      successTakeaway: 'Commande enregistrée ! Vous pourrez payer au retrait.',
      errorOrder: 'Erreur lors de la commande',
    },
    // Common
    common: {
      loading: 'Chargement...',
      error: 'Erreur',
      save: 'Enregistrer',
      cancel: 'Annuler',
      delete: 'Supprimer',
      edit: 'Modifier',
      add: 'Ajouter',
      back: 'Retour',
      confirm: 'Confirmer',
      yes: 'Oui',
      no: 'Non',
    },
    // Settings
    settings: {
      title: 'Paramètres du Restaurant',
      subtitle: 'Configurez les informations de votre établissement',
      restaurantInfo: 'Informations Générales',
      name: 'Nom du restaurant',
      description: 'Description',
      contact: 'Coordonnées',
      address: 'Adresse',
      phone: 'Téléphone',
      email: 'E-mail',
      mapsSection: 'Google Maps & Carte',
      mapPreview: 'Aperçu carte',
      mapsUrl: 'Lien Google Maps',
      mapsUrlHint: "Lien de la page Google Maps (pour le footer et le bouton 'Voir sur Maps')",
      mapEmbed: "URL d'intégration carte",
      mapEmbedHint: "URL d'intégration iframe (OpenStreetMap ou Google Maps Embed). Visible dans la page À Propos.",
      hours: "Horaires d'ouverture",
      weekdayOpen: 'Ouverture semaine',
      weekdayClose: 'Fermeture semaine',
      sundayOpen: 'Ouverture dimanche',
      sundayClose: 'Fermeture dimanche',
      weekdays: 'Lundi – Samedi',
      sunday: 'Dimanche',
      saveSuccess: 'Paramètres sauvegardés avec succès !',
      saveError: 'Erreur lors de la sauvegarde',
      save: 'Sauvegarder les modifications',
      saving: 'Sauvegarde en cours...',
      reset: 'Réinitialiser par défaut',
      resetConfirm: 'Réinitialiser toutes les informations aux valeurs par défaut ?',
      resetSuccess: 'Réinitialisé aux valeurs par défaut',
      unsavedChanges: 'Modifications non sauvegardées',
      clickToSave: 'Cliquez sur "Sauvegarder" pour appliquer',
      upToDate: 'Tout est à jour',
      synced: 'Les paramètres sont synchronisés',
      preview: 'Aperçu en direct',
      currentStatus: 'Statut actuel',
      open: 'Ouvert maintenant',
      closed: 'Fermé actuellement',
      liveUpdate: 'Les modifications s\'appliquent immédiatement sur tout le site',
      logoUrl: 'URL du logo',
      socialLinks: 'Réseaux sociaux',
      facebook: 'Facebook',
      instagram: 'Instagram',
    },
  },

  nl: {
    // Navbar
    nav: {
      dashboard: 'Dashboard',
      users: 'Gebruikers',
      products: 'Producten',
      orders: 'Bestellingen',
      menu: 'Menu',
      myOrders: 'Mijn bestellingen',
      myReservations: 'Mijn reserveringen',
      myReviews: 'Mijn beoordelingen',
      payments: 'Betalingen',
      ordersToServe: 'Te serveren bestellingen',
      tableManagement: 'Tafelsbeheer',
      ordersToPrep: 'Te bereiden bestellingen',
      supplyOrders: 'Inkooporders',
      mySupplies: 'Mijn leveringen',
      profile: 'Mijn profiel',
      logout: 'Uitloggen',
      about: 'Over Ons',
      restaurantSettings: 'Instellingen',
    },
    // Footer
    footer: {
      description: 'Volledig beheerssysteem voor snackbars. Beheer van bestellingen, reserveringen, voorraad en meer.',
      quickLinks: 'Snelle links',
      about: 'Over ons',
      contact: 'Contact',
      info: 'Informatie',
      rights: 'Alle rechten voorbehouden.',
      devWith: 'Ontwikkeld met React en Spring Boot',
      address: 'Adres',
      phone: 'Telefoon',
      email: 'E-mail',
      hours: 'Openingstijden',
      hoursDetails: 'Ma-Za: 10:00 - 22:00 | Zo: 12:00 - 21:00',
      open: 'Nu open',
      closed: 'Momenteel gesloten',
      location: 'Onze locatie',
      weekdays: 'Ma – Za',
      sunday: 'Zo',
      mapsOpen: 'Openen in Google Maps',
    },
    // Dashboard
    dashboard: {
      title: 'Beheerdashboard',
      users: 'Gebruikers',
      employees: 'Medewerkers',
      providers: 'Leveranciers',
      products: 'Producten',
      clientOrders: 'Klantbestellingen',
      supplierOrders: 'Leveranciersbestellingen',
      tables: 'Tafels',
      stockAlerts: 'Voorraadwaarschuwingen',
      revenue: 'Omzet',
      tickets: 'Tickets',
      manageUsers: 'Gebruikers beheren',
      manageStaff: 'Personeel beheren',
      manageProviders: 'Leveranciers beheren',
      manageStock: 'Voorraad beheren',
      viewOrders: 'Bestellingen bekijken',
      viewSupplies: 'Leveringen bekijken',
      manageHall: 'Zaal beheren',
      viewAlerts: 'Waarschuwingen bekijken',
      financialDetails: 'Financiële details',
      manageTickets: 'Tickets beheren',
      quickActions: 'Snelle acties',
      newProduct: 'Nieuw product',
      newEmployee: 'Nieuwe medewerker',
      newProvider: 'Nieuwe leverancier',
      orderStock: 'Voorraad bestellen',
      newTable: 'Nieuwe tafel',
      recentActivity: 'Recente activiteit',
      recentOrders: 'Recente bestellingen',
      recentReviews: 'Laatste klantbeoordelingen',
      topProducts: 'Topproducten',
      reservationStats: 'Reserveringsstatistieken',
      ordersByStatus: 'Bestellingen per status',
      todayRevenue: 'Omzet vandaag',
      totalRevenue: 'Totale omzet',
      avgOrderValue: 'Gemiddelde bestelling',
      noReviews: 'Geen beoordelingen beschikbaar',
      noOrders: 'Geen recente bestellingen',
      loading: 'Laden...',
      refreshEvery: 'Vernieuwen elke 30 sec',
      ordersActive: 'Actief',
      ordersClosed: 'Klaar',
      ordersServed: 'Geserveerd',
      ordersCancelled: 'Geannuleerd',
      booked: 'Gereserveerd',
      completed: 'Voltooid',
      cancelled: 'Geannuleerd',
      noData: 'Geen gegevens',
      refresh: 'Vernieuwen',
      ordersCount: 'bestellingen',
      today: 'Vandaag',
      perOrder: 'Per bestelling',
      viewAll: 'Alles bekijken →',
      last5: 'Laatste 5',
      weeklyOrders: 'Bestellingen - Laatste 7 dagen',
      weeklyRevenue: 'Omzet - 7 dagen',
      totalLabel: 'Totaal:',
      totalReservations: 'Totaal reserveringen',
      onSite: 'Ter plaatse',
      takeaway: 'Afhalen',
    },
    // Menu
    menu: {
      title: 'Tijd om te',
      titleHighlight: 'Genieten!',
      subtitle: 'Ontdek onze heerlijke gerechten, bereid met passie en geserveerd met een glimlach.',
      search: 'Honger? Zoek hier...',
      allCategories: 'Alle categorieën',
      ourDishes: 'Onze Gerechten',
      freshDrinks: 'Verse Dranken',
      nothingFound: 'Oeps! Niets gevonden',
      tryAnother: 'Probeer een andere zoekopdracht of categorie',
      checkout: 'Bestelling plaatsen',
      article: 'Artikel',
      articles: 'Artikelen',
      productDetails: 'Productdetails',
      unitPrice: 'Eenheidsprijs',
      availability: 'Beschikbaarheid',
      outOfStock: 'Niet op voorraad',
      lowStock: 'Lage voorraad',
      available: 'Beschikbaar',
      description: 'Beschrijving',
      allergens: 'Allergenen',
      noAllergens: 'Geen allergenen aangegeven',
      yourRating: 'Uw beoordeling',
      ratedWith: 'U heeft',
      stars: 'sterren gegeven',
      addToCart: 'Aan winkelwagen toevoegen',
      unavailable: 'Niet beschikbaar',
      close: 'Sluiten',
      chooseSauces: 'Kies uw sauzen',
      chooseViandes: 'Kies uw vlees',
      chooseDesserts: 'Kies een dessert',
      extras: "Extra's & Opties",
      basePrice: 'Basisprijs',
      extrasTotal: "Extra's totaal",
      totalPrice: 'Totaalprijs',
      viewDetails: 'Details bekijken',
      outOfStockMsg: 'Sorry, dit product is niet op voorraad.',
    },
    // ProductCard
    card: {
      outOfStock: 'Uitverkocht',
      lowStock: 'Lage voorraad',
      seeDetails: 'Details bekijken',
      addToCart: 'Aan winkelwagen toevoegen',
      inCart: 'In winkelwagen',
      unavailable: 'Niet beschikbaar',
      remaining: 'resterend',
      exhausted: 'Uitgeput',
    },
    // Chatbot
    chatbot: {
      title: 'AI Klantenservice',
      online: 'Online',
      welcome: 'Hallo! Ik ben de assistent van Snack Tiegni Bernard. Hoe kan ik u vandaag helpen?',
      placeholder: 'Schrijf uw bericht...',
      generatedByAI: 'Gegenereerd door AI - Kan fouten bevatten',
      retry: 'Opnieuw proberen',
      unstableConnection: 'Onstabiele verbinding...',
      errorMessage: 'Sorry, ik ondervind technische problemen bij het beantwoorden. Probeer het opnieuw.',
      openChat: 'Chat openen met klantenservice',
      closeChat: 'Chat sluiten',
      send: 'Verzenden',
      voiceInput: 'Spraakinvoer',
      listening: 'Ik luister...',
      voiceError: 'Microfoon fout - controleer de rechten',
      voiceNotSupported: 'Spraakinvoer wordt niet ondersteund door deze browser',
      liveVoice: 'Live Spraakchat',
      voiceFirefoxNotSupported: 'Firefox ondersteunt geen spraakherkenning. Gebruik Chrome, Edge of Safari.',
      voiceMicDenied: 'Toegang tot microfoon geweigerd. Controleer de browserinstellingen.',
      voiceMicNotFound: 'Geen microfoon gevonden op dit apparaat.',
    },
    // About
    about: {
      heroTitle: 'Snack Tiegni Bernard',
      heroSubtitle: 'Uw restaurant in het hart van Brussel, België',
      story: 'Ons Verhaal',
      storyText: 'Snack Tiegni Bernard is een modern restaurant dat authentieke Belgische smaken combineert met internationale culinaire inspiraties. Gelegen in het hart van Brussel bieden wij een unieke gastronomische ervaring met verse, kwaliteitsproducten en een vriendelijke bediening.',
      mission: 'Onze Missie',
      missionText: 'Onze klanten een uitzonderlijke culinaire ervaring bieden in een warme sfeer, met snelle bediening en betaalbare prijzen voor iedereen.',
      contact: 'Contact',
      address: 'Adres',
      phone: 'Telefoon',
      email: 'E-mail',
      hours: 'Openingstijden',
      weekdays: 'Maandag – Zaterdag',
      sunday: 'Zondag',
      weekdaysHours: '10:00 – 22:00',
      sundayHours: '12:00 – 21:00',
      open: 'Nu open',
      closed: 'Momenteel gesloten',
      location: 'Onze Locatie',
      mapLink: 'Bekijken op Google Maps',
      values: 'Onze Waarden',
      quality: 'Kwaliteit',
      qualityDesc: 'Dagelijks zorgvuldig geselecteerde verse ingrediënten',
      service: 'Service',
      serviceDesc: 'Hartelijke ontvangst en team toegewijd aan uw tevredenheid',
      speed: 'Snelheid',
      speedDesc: 'Snelle bereiding zonder concessies te doen aan kwaliteit',
      team: 'Ons Team',
      teamDesc: 'Gepassioneerde professionals tot uw dienst',
      viewMenu: 'Bekijk ons menu',
      orderNow: 'Nu bestellen',
      contactUs: 'Neem contact op',
      followUs: 'Volg ons',
      copyright: 'Alle rechten voorbehouden',
      locationCity: 'Brussel, België',
      roleAdmin: 'Beheerder',
      roleAdminDesc: 'Globaal toezicht op het restaurant en de activiteiten',
      roleCashier: 'Kassier',
      roleCashierDesc: 'Betalingsbeheer en validatie van transacties',
      roleCook: 'Kok',
      roleCookDesc: 'Bereiding van bestellingen en beheer van de keuken',
      roleWaiter: 'Ober',
      roleWaiterDesc: 'Bediening in de zaal, tafeltoewijzing en reserveringen',
      mapInteractive: 'Interactieve kaart',
      viewOnMaps: 'Bekijken op Google Maps',
    },
    // Checkout
    checkout: {
      title: 'Uw Winkelwagen',
      summary: 'Overzicht',
      empty: 'Uw winkelwagen is leeg',
      emptyDesc: 'Voeg producten toe vanuit het menu om te beginnen',
      backToMenu: 'Terug naar menu',
      orderType: 'Type bestelling',
      paymentMethod: 'Betalingsmethode',
      documentType: 'Type document',
      pickupTime: 'Afhaaltijd (optioneel)',
      pickupHint: 'Laat leeg voor onmiddellijk afhalen',
      guestCount: 'Aantal gasten',
      guestHint: 'De kelner wijst u een tafel toe',
      total: 'Totaal',
      base: 'Subtotaal',
      extras: "Extra's",
      order: 'Bestellen',
      pay: 'Betalen',
      processing: 'Verwerken...',
      includes: 'inbegrepen',
      ordersSection: 'Bestelde artikelen',
      orderOptions: 'Bestelopties',
      typeLabel: 'Type',
      securePayment: 'Veilige betaling · Gegevens beschermd',
      paymentLabel: 'Betaling',
      documentLabel: 'Document',
      retrievalLabel: 'Ophalen',
      successOnSite: 'Bestelling naar de keuken gestuurd!',
      successTakeaway: 'Bestelling geregistreerd! U kunt betalen bij het ophalen.',
      errorOrder: 'Fout bij het plaatsen van de bestelling',
    },
    // Common
    common: {
      loading: 'Laden...',
      error: 'Fout',
      save: 'Opslaan',
      cancel: 'Annuleren',
      delete: 'Verwijderen',
      edit: 'Bewerken',
      add: 'Toevoegen',
      back: 'Terug',
      confirm: 'Bevestigen',
      yes: 'Ja',
      no: 'Nee',
    },
    // Settings
    settings: {
      title: 'Restaurantinstellingen',
      subtitle: 'Configureer de informatie van uw vestiging',
      restaurantInfo: 'Algemene informatie',
      name: 'Restaurantnaam',
      description: 'Beschrijving',
      contact: 'Contactgegevens',
      address: 'Adres',
      phone: 'Telefoon',
      email: 'E-mail',
      mapsSection: 'Google Maps & Kaart',
      mapPreview: 'Kaartvoorbeeld',
      mapsUrl: 'Google Maps-link',
      mapsUrlHint: "Link naar de Google Maps-pagina (voor de footer en de knop 'Bekijken op Maps')",
      mapEmbed: 'Kaartinsluitings-URL',
      mapEmbedHint: 'iFrame-insluitings-URL (OpenStreetMap of Google Maps Embed). Zichtbaar op de Over Ons-pagina.',
      hours: 'Openingstijden',
      weekdayOpen: 'Opening doordeweeks',
      weekdayClose: 'Sluiting doordeweeks',
      sundayOpen: 'Opening zondag',
      sundayClose: 'Sluiting zondag',
      weekdays: 'Maandag – Zaterdag',
      sunday: 'Zondag',
      saveSuccess: 'Instellingen succesvol opgeslagen!',
      saveError: 'Fout bij opslaan',
      save: 'Wijzigingen opslaan',
      saving: 'Opslaan...',
      reset: 'Standaard herstellen',
      resetConfirm: 'Alle informatie terugzetten naar standaardwaarden?',
      resetSuccess: 'Ingesteld op standaardwaarden',
      unsavedChanges: 'Niet-opgeslagen wijzigingen',
      clickToSave: 'Klik op "Opslaan" om toe te passen',
      upToDate: 'Alles up-to-date',
      synced: 'Instellingen zijn gesynchroniseerd',
      preview: 'Live voorbeeld',
      currentStatus: 'Huidige status',
      open: 'Nu open',
      closed: 'Momenteel gesloten',
      liveUpdate: 'Wijzigingen worden onmiddellijk op de hele site toegepast',
      logoUrl: 'Logo-URL',
      socialLinks: 'Sociale media',
      facebook: 'Facebook',
      instagram: 'Instagram',
    },
  },

  de: {
    // Navbar
    nav: {
      dashboard: 'Dashboard',
      users: 'Benutzer',
      products: 'Produkte',
      orders: 'Bestellungen',
      menu: 'Speisekarte',
      myOrders: 'Meine Bestellungen',
      myReservations: 'Meine Reservierungen',
      myReviews: 'Meine Bewertungen',
      payments: 'Zahlungen',
      ordersToServe: 'Zu servierende Bestellungen',
      tableManagement: 'Tischverwaltung',
      ordersToPrep: 'Zu bereitende Bestellungen',
      supplyOrders: 'Lieferbestellungen',
      mySupplies: 'Meine Lieferungen',
      profile: 'Mein Profil',
      logout: 'Abmelden',
      about: 'Über Uns',
      restaurantSettings: 'Einstellungen',
    },
    // Footer
    footer: {
      description: 'Vollständiges Verwaltungssystem für Imbissbuden. Verwaltung von Bestellungen, Reservierungen, Lagerbestand und mehr.',
      quickLinks: 'Schnelle Links',
      about: 'Über uns',
      contact: 'Kontakt',
      info: 'Informationen',
      rights: 'Alle Rechte vorbehalten.',
      devWith: 'Entwickelt mit React und Spring Boot',
      address: 'Adresse',
      phone: 'Telefon',
      email: 'E-Mail',
      hours: 'Öffnungszeiten',
      hoursDetails: 'Mo-Sa: 10:00 - 22:00 Uhr | So: 12:00 - 21:00 Uhr',
      open: 'Jetzt geöffnet',
      closed: 'Derzeit geschlossen',
      location: 'Unser Standort',
      weekdays: 'Mo – Sa',
      sunday: 'So',
      mapsOpen: 'In Google Maps öffnen',
    },
    // Dashboard
    dashboard: {
      title: 'Administrator-Dashboard',
      users: 'Benutzer',
      employees: 'Mitarbeiter',
      providers: 'Lieferanten',
      products: 'Produkte',
      clientOrders: 'Kundenbestellungen',
      supplierOrders: 'Lieferantenbestellungen',
      tables: 'Tische',
      stockAlerts: 'Lagerbestandswarnungen',
      revenue: 'Umsatz',
      tickets: 'Tickets',
      manageUsers: 'Benutzer verwalten',
      manageStaff: 'Personal verwalten',
      manageProviders: 'Lieferanten verwalten',
      manageStock: 'Lager verwalten',
      viewOrders: 'Bestellungen anzeigen',
      viewSupplies: 'Lieferungen anzeigen',
      manageHall: 'Saal verwalten',
      viewAlerts: 'Warnungen anzeigen',
      financialDetails: 'Finanzdetails',
      manageTickets: 'Tickets verwalten',
      quickActions: 'Schnellaktionen',
      newProduct: 'Neues Produkt',
      newEmployee: 'Neuer Mitarbeiter',
      newProvider: 'Neuer Lieferant',
      orderStock: 'Lager bestellen',
      newTable: 'Neuer Tisch',
      recentActivity: 'Letzte Aktivitäten',
      recentOrders: 'Letzte Bestellungen',
      recentReviews: 'Letzte Kundenbewertungen',
      topProducts: 'Top-Produkte',
      reservationStats: 'Reservierungsstatistik',
      ordersByStatus: 'Bestellungen nach Status',
      todayRevenue: 'Heutiger Umsatz',
      totalRevenue: 'Gesamtumsatz',
      avgOrderValue: 'Durchschnittlicher Warenkorbwert',
      noReviews: 'Keine Bewertungen verfügbar',
      noOrders: 'Keine neueren Bestellungen',
      loading: 'Laden...',
      refreshEvery: 'Aktualisierung alle 30 Sek',
      ordersActive: 'Aktiv',
      ordersClosed: 'Bereit',
      ordersServed: 'Serviert',
      ordersCancelled: 'Storniert',
      booked: 'Gebucht',
      completed: 'Abgeschlossen',
      cancelled: 'Storniert',
      noData: 'Keine Daten',
      refresh: 'Aktualisieren',
      ordersCount: 'Bestellungen',
      today: 'Heute',
      perOrder: 'Pro Bestellung',
      viewAll: 'Alle anzeigen →',
      last5: 'Letzte 5',
      weeklyOrders: 'Bestellungen - Letzte 7 Tage',
      weeklyRevenue: 'Umsatz - 7 Tage',
      totalLabel: 'Gesamt:',
      totalReservations: 'Reservierungen gesamt',
      onSite: 'Vor Ort',
      takeaway: 'Zum Mitnehmen',
    },
    // Menu
    menu: {
      title: 'Zeit zu',
      titleHighlight: 'Genießen!',
      subtitle: 'Entdecken Sie unsere köstlichen Gerichte, liebevoll zubereitet und mit einem Lächeln serviert.',
      search: 'Hunger? Hier suchen...',
      allCategories: 'Alle Kategorien',
      ourDishes: 'Unsere Gerichte',
      freshDrinks: 'Frische Getränke',
      nothingFound: 'Hoppla! Nichts gefunden',
      tryAnother: 'Versuchen Sie eine andere Suche oder Kategorie',
      checkout: 'Bestellung aufgeben',
      article: 'Artikel',
      articles: 'Artikel',
      productDetails: 'Produktdetails',
      unitPrice: 'Einzelpreis',
      availability: 'Verfügbarkeit',
      outOfStock: 'Nicht vorrätig',
      lowStock: 'Geringer Lagerbestand',
      available: 'Verfügbar',
      description: 'Beschreibung',
      allergens: 'Allergene',
      noAllergens: 'Keine deklarierten Allergene',
      yourRating: 'Ihre Bewertung',
      ratedWith: 'Sie haben',
      stars: 'Sterne vergeben',
      addToCart: 'In den Warenkorb',
      unavailable: 'Nicht verfügbar',
      close: 'Schließen',
      chooseSauces: 'Wählen Sie Ihre Soßen',
      chooseViandes: 'Wählen Sie Ihr Fleisch',
      chooseDesserts: 'Wählen Sie ein Dessert',
      extras: 'Extras & Optionen',
      basePrice: 'Grundpreis',
      extrasTotal: 'Extras gesamt',
      totalPrice: 'Gesamtpreis',
      viewDetails: 'Details ansehen',
      outOfStockMsg: 'Entschuldigung, dieses Produkt ist nicht vorrätig.',
    },
    // ProductCard
    card: {
      outOfStock: 'Ausverkauft',
      lowStock: 'Niedriger Lagerbestand',
      seeDetails: 'Details ansehen',
      addToCart: 'In den Warenkorb',
      inCart: 'Im Warenkorb',
      unavailable: 'Nicht verfügbar',
      remaining: 'verbleibend',
      exhausted: 'Ausgeschöpft',
    },
    // Chatbot
    chatbot: {
      title: 'KI-Kundenservice',
      online: 'Online',
      welcome: 'Hallo! Ich bin der Assistent des Snack Tiegni Bernard. Wie kann ich Ihnen heute helfen?',
      placeholder: 'Schreiben Sie Ihre Nachricht...',
      generatedByAI: 'Von KI generiert - Kann Fehler enthalten',
      retry: 'Erneut versuchen',
      unstableConnection: 'Instabile Verbindung...',
      errorMessage: 'Entschuldigung, ich habe technische Schwierigkeiten bei der Beantwortung. Bitte versuchen Sie es erneut.',
      openChat: 'Chat mit Kundenservice öffnen',
      closeChat: 'Chat schließen',
      send: 'Senden',
      voiceInput: 'Spracheingabe',
      listening: 'Ich höre zu...',
      voiceError: 'Mikrofonfehler - Berechtigungen prüfen',
      voiceNotSupported: 'Spracheingabe wird von diesem Browser nicht unterstützt',
      liveVoice: 'Live-Sprachchat',
      voiceFirefoxNotSupported: 'Firefox unterstützt keine Spracherkennung. Verwenden Sie Chrome, Edge oder Safari.',
      voiceMicDenied: 'Mikrofonzugriff verweigert. Überprüfen Sie Ihre Browsereinstellungen.',
      voiceMicNotFound: 'Kein Mikrofon auf diesem Gerät gefunden.',
    },
    // About
    about: {
      heroTitle: 'Snack Tiegni Bernard',
      heroSubtitle: 'Ihr Restaurant im Herzen von Brüssel, Belgien',
      story: 'Unsere Geschichte',
      storyText: 'Der Snack Tiegni Bernard ist ein modernes Restaurant, das authentische belgische Aromen mit internationalen Kücheninspirationen verbindet. Im Herzen Brüssels gelegen, bieten wir ein einzigartiges Gastronomieerlebnis mit frischen Qualitätsprodukten und herzlichem Service.',
      mission: 'Unsere Mission',
      missionText: 'Unseren Gästen ein außergewöhnliches kulinarisches Erlebnis in einer herzlichen Atmosphäre zu bieten – mit schnellem Service und erschwinglichen Preisen für alle.',
      contact: 'Kontakt',
      address: 'Adresse',
      phone: 'Telefon',
      email: 'E-Mail',
      hours: 'Öffnungszeiten',
      weekdays: 'Montag – Samstag',
      sunday: 'Sonntag',
      weekdaysHours: '10:00 – 22:00 Uhr',
      sundayHours: '12:00 – 21:00 Uhr',
      open: 'Jetzt geöffnet',
      closed: 'Derzeit geschlossen',
      location: 'Unser Standort',
      mapLink: 'In Google Maps öffnen',
      values: 'Unsere Werte',
      quality: 'Qualität',
      qualityDesc: 'Täglich sorgfältig ausgewählte frische Zutaten',
      service: 'Service',
      serviceDesc: 'Herzlicher Empfang und Team, das sich Ihrer Zufriedenheit widmet',
      speed: 'Schnelligkeit',
      speedDesc: 'Schnelle Zubereitung ohne Kompromisse bei der Qualität',
      team: 'Unser Team',
      teamDesc: 'Leidenschaftliche Profis zu Ihren Diensten',
      viewMenu: 'Unsere Speisekarte',
      orderNow: 'Jetzt bestellen',
      contactUs: 'Kontakt aufnehmen',
      followUs: 'Folgen Sie uns',
      copyright: 'Alle Rechte vorbehalten',
      locationCity: 'Brüssel, Belgien',
      roleAdmin: 'Administrator',
      roleAdminDesc: 'Globale Überwachung des Restaurants und der Abläufe',
      roleCashier: 'Kassierer',
      roleCashierDesc: 'Zahlungsabwicklung und Transaktionsvalidierung',
      roleCook: 'Koch',
      roleCookDesc: 'Zubereitung von Bestellungen und Küchenmanagement',
      roleWaiter: 'Kellner',
      roleWaiterDesc: 'Service im Saal, Tischzuweisung und Reservierungen',
      mapInteractive: 'Interaktive Karte',
      viewOnMaps: 'In Google Maps öffnen',
    },
    // Checkout
    checkout: {
      title: 'Ihr Warenkorb',
      summary: 'Zusammenfassung',
      empty: 'Ihr Warenkorb ist leer',
      emptyDesc: 'Fügen Sie Produkte aus der Speisekarte hinzu, um zu beginnen',
      backToMenu: 'Zurück zur Speisekarte',
      orderType: 'Bestellungsart',
      paymentMethod: 'Zahlungsmethode',
      documentType: 'Dokumententyp',
      pickupTime: 'Abholzeit (optional)',
      pickupHint: 'Leer lassen für sofortige Abholung',
      guestCount: 'Anzahl der Gäste',
      guestHint: 'Der Kellner weist Ihnen einen Tisch zu',
      total: 'Gesamt',
      base: 'Zwischensumme',
      extras: 'Extras',
      order: 'Bestellen',
      pay: 'Bezahlen',
      processing: 'Verarbeitung...',
      includes: 'inklusive',
      ordersSection: 'Bestellte Artikel',
      orderOptions: 'Bestelloptionen',
      typeLabel: 'Typ',
      securePayment: 'Sichere Zahlung · Daten geschützt',
      paymentLabel: 'Zahlung',
      documentLabel: 'Dokument',
      retrievalLabel: 'Abholung',
      successOnSite: 'Bestellung in die Küche gesendet!',
      successTakeaway: 'Bestellung registriert! Sie können bei der Abholung bezahlen.',
      errorOrder: 'Fehler bei der Bestellung',
    },
    // Common
    common: {
      loading: 'Laden...',
      error: 'Fehler',
      save: 'Speichern',
      cancel: 'Abbrechen',
      delete: 'Löschen',
      edit: 'Bearbeiten',
      add: 'Hinzufügen',
      back: 'Zurück',
      confirm: 'Bestätigen',
      yes: 'Ja',
      no: 'Nein',
    },
    // Settings
    settings: {
      title: 'Restaurant-Einstellungen',
      subtitle: 'Konfigurieren Sie die Informationen Ihres Restaurants',
      restaurantInfo: 'Allgemeine Informationen',
      name: 'Restaurantname',
      description: 'Beschreibung',
      contact: 'Kontaktdaten',
      address: 'Adresse',
      phone: 'Telefon',
      email: 'E-Mail',
      mapsSection: 'Google Maps & Karte',
      mapPreview: 'Kartenvorschau',
      mapsUrl: 'Google Maps-Link',
      mapsUrlHint: "Link zur Google Maps-Seite (für die Fußzeile und die Schaltfläche 'Auf Maps anzeigen')",
      mapEmbed: 'Karten-Einbettungs-URL',
      mapEmbedHint: 'iFrame-Einbettungs-URL (OpenStreetMap oder Google Maps Embed). Sichtbar auf der Über-uns-Seite.',
      hours: 'Öffnungszeiten',
      weekdayOpen: 'Öffnung wochentags',
      weekdayClose: 'Schließung wochentags',
      sundayOpen: 'Öffnung sonntags',
      sundayClose: 'Schließung sonntags',
      weekdays: 'Montag – Samstag',
      sunday: 'Sonntag',
      saveSuccess: 'Einstellungen erfolgreich gespeichert!',
      saveError: 'Fehler beim Speichern',
      save: 'Änderungen speichern',
      saving: 'Wird gespeichert...',
      reset: 'Auf Standard zurücksetzen',
      resetConfirm: 'Alle Informationen auf Standardwerte zurücksetzen?',
      resetSuccess: 'Auf Standardwerte zurückgesetzt',
      unsavedChanges: 'Nicht gespeicherte Änderungen',
      clickToSave: 'Klicken Sie auf "Speichern" zum Anwenden',
      upToDate: 'Alles aktuell',
      synced: 'Einstellungen sind synchronisiert',
      preview: 'Live-Vorschau',
      currentStatus: 'Aktueller Status',
      open: 'Jetzt geöffnet',
      closed: 'Derzeit geschlossen',
      liveUpdate: 'Änderungen werden sofort auf der gesamten Website angewendet',
      logoUrl: 'Logo-URL',
      socialLinks: 'Soziale Medien',
      facebook: 'Facebook',
      instagram: 'Instagram',
    },
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('app_language') || 'fr';
  });

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('app_language', lang);
  };

  const t = (key) => {
    const keys = key.split('.');
    let result = translations[language];
    for (const k of keys) {
      if (result === undefined) return key;
      result = result[k];
    }
    return result || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, translations }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};

export default LanguageContext;
